# Generated by Django 6.0.2 on 2026-02-12 15:48

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def ensure_proxyfw_schema(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE SCHEMA IF NOT EXISTS proxyfw;")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(ensure_proxyfw_schema, migrations.RunPython.noop),
        migrations.CreateModel(
            name='HttpMethod',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('method_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'http_method',
                'constraints': [models.CheckConstraint(condition=models.Q(('method', django.db.models.functions.text.Upper('method'))), name='http_method_uppercase_check'), models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('method',), name='http_method_method_active_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policy',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('name',), name='policy_name_active_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP')], max_length=3)),
                ('port', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('protocol', 'port'), name='service_protocol_port_active_uniq')],
            },
        ),
        migrations.CreateModel(
            name='UrlCategory',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'url_category',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('name',), name='url_category_name_active_uniq')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('auth_type', models.CharField(choices=[('LOCAL', 'LOCAL'), ('LDAP', 'LDAP'), ('OIDC', 'OIDC'), ('SAML', 'SAML'), ('OTHER', 'OTHER')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('username',), name='users_username_active_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('zone_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'zone',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('zone_name',), name='zone_zone_name_active_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('condition', models.JSONField()),
                ('action', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY'), ('ALERT', 'ALERT'), ('LOG_ONLY', 'LOG_ONLY')], max_length=10)),
                ('priority', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(db_column='policy_id', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='control.policy')),
            ],
            options={
                'db_table': 'rule',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('policy', 'priority'), name='rule_policy_priority_active_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scheme', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('path', models.TextField()),
                ('query', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='control.urlcategory')),
            ],
            options={
                'db_table': 'url',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('scheme', 'host', 'port', 'path', 'query'), name='url_scheme_host_port_path_query_active_uniq')],
            },
        ),
    ]
