# Generated by Django 6.0.2 on 2026-02-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpMethod',
            fields=[
                ('method_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'http_method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'policy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('condition', models.JSONField()),
                ('action', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY'), ('ALERT', 'ALERT'), ('LOG_ONLY', 'LOG_ONLY')], max_length=10)),
                ('priority', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP')], max_length=3)),
                ('port', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scheme', models.CharField(max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('path', models.TextField()),
                ('query', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UrlCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'url_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('auth_type', models.CharField(choices=[('LOCAL', 'LOCAL'), ('LDAP', 'LDAP'), ('OIDC', 'OIDC'), ('SAML', 'SAML'), ('OTHER', 'OTHER')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
    ]
