# Generated by Django 6.0.2 on 2026-02-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.CharField(choices=[('ALLOW', 'PERMITIR'), ('DENY', 'BLOQUEAR'), ('ALERT', 'ALERTAR'), ('LOG_ONLY', 'SOLO_REGISTRO')], max_length=10),
        ),
    ]
