# Generated by Django 6.0.2 on 2026-02-12 23:31

import django.db.models.deletion
from django.db import migrations, models
from datetime import time


def _parse_hhmm(value):
    if not value or not isinstance(value, str) or ":" not in value:
        return None
    try:
        hh, mm = value.split(":", 1)
        return time(int(hh), int(mm))
    except (TypeError, ValueError):
        return None


def migrate_rule_condition_to_attributes(apps, schema_editor):
    Rule = apps.get_model("control", "Rule")

    for rule in Rule.objects.all():
        condition = rule.condition if isinstance(rule.condition, dict) else {}
        match = condition.get("match") if isinstance(condition.get("match"), dict) else {}
        time_cfg = condition.get("time") if isinstance(condition.get("time"), dict) else {}

        category_ids = match.get("url_categories") or []
        first_category = None
        if isinstance(category_ids, list) and category_ids:
            try:
                first_category = int(category_ids[0])
            except (TypeError, ValueError):
                first_category = None

        days = time_cfg.get("days") or []
        days_csv = ",".join([str(d).strip().upper() for d in days if str(d).strip()])

        rule.url_category_id = first_category
        rule.note = (condition.get("note") or "").strip()
        rule.schedule_days = days_csv
        rule.schedule_start = _parse_hhmm(time_cfg.get("start"))
        rule.schedule_end = _parse_hhmm(time_cfg.get("end"))
        rule.schedule_tz = (time_cfg.get("tz") or "America/Guayaquil").strip()
        rule.save(
            update_fields=[
                "url_category",
                "note",
                "schedule_days",
                "schedule_start",
                "schedule_end",
                "schedule_tz",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_rule_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rule',
            name='schedule_days',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rule',
            name='schedule_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='schedule_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='schedule_tz',
            field=models.CharField(blank=True, default='America/Guayaquil', max_length=80),
        ),
        migrations.AddField(
            model_name='rule',
            name='url_category',
            field=models.ForeignKey(blank=True, db_column='url_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='control.urlcategory'),
        ),
        migrations.RunPython(migrate_rule_condition_to_attributes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='rule',
            name='condition',
        ),
    ]
