from django.urls import path

from .views import (
    category_create,
    category_delete,
    category_edit,
    category_list,
    control_index,
    edit_rule,
    method_create,
    method_delete,
    method_edit,
    method_list,
    policy_create,
    policy_delete,
    policy_edit,
    policy_list,
    service_create,
    service_delete,
    service_edit,
    service_list,
    url_create,
    url_delete,
    url_edit,
    url_list,
    zone_create,
    zone_delete,
    zone_edit,
    zone_list,
    rule_list,
    rule_create,
    rule_edit,
    rule_apply,
    rule_toggle,
)

urlpatterns = [
    path("", control_index, name="control_index"),
    path("rules/", rule_list, name="rule_list"),
    path("rules/create/", rule_create, name="rule_create"),
    path("rules/apply/", rule_apply, name="rule_apply"),
    path("rules/<int:rule_id>/edit/", rule_edit, name="rule_edit"),
    path("rules/<int:rule_id>/toggle/", rule_toggle, name="rule_toggle"),
    path("politicas/", policy_list, name="policy_list"),
    path("politicas/nueva/", policy_create, name="policy_create"),
    path("politicas/<int:policy_id>/editar/", policy_edit, name="policy_edit"),
    path("politicas/<int:policy_id>/eliminar/", policy_delete, name="policy_delete"),
    path("categorias/", category_list, name="category_list"),
    path("categorias/nueva/", category_create, name="category_create"),
    path("categorias/<int:category_id>/editar/", category_edit, name="category_edit"),
    path("categorias/<int:category_id>/eliminar/", category_delete, name="category_delete"),
    path("urls/", url_list, name="url_list"),
    path("urls/nueva/", url_create, name="url_create"),
    path("urls/<int:url_id>/editar/", url_edit, name="url_edit"),
    path("urls/<int:url_id>/eliminar/", url_delete, name="url_delete"),
    path("metodos-http/", method_list, name="method_list"),
    path("metodos-http/nuevo/", method_create, name="method_create"),
    path("metodos-http/<int:method_id>/editar/", method_edit, name="method_edit"),
    path("metodos-http/<int:method_id>/eliminar/", method_delete, name="method_delete"),
    path("zonas/", zone_list, name="zone_list"),
    path("zonas/nueva/", zone_create, name="zone_create"),
    path("zonas/<int:zone_id>/editar/", zone_edit, name="zone_edit"),
    path("zonas/<int:zone_id>/eliminar/", zone_delete, name="zone_delete"),
    path("servicios/", service_list, name="service_list"),
    path("servicios/nuevo/", service_create, name="service_create"),
    path("servicios/<int:service_id>/editar/", service_edit, name="service_edit"),
    path("servicios/<int:service_id>/eliminar/", service_delete, name="service_delete"),
    path("reglas/<int:rule_id>/editar/", edit_rule, name="edit_rule"),
]
