# Generated by Django 6.0.2 on 2026-02-12 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('cache_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.BigIntegerField()),
                ('last_accessed', models.DateTimeField()),
                ('expiration_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'cache_entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('error_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='ERROR', max_length=8)),
                ('message', models.TextField()),
                ('component', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'error_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FirewallEvent',
            fields=[
                ('fw_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('action', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY'), ('ALERT', 'ALERT'), ('LOG_ONLY', 'LOG_ONLY')], max_length=10)),
                ('nat_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'firewall_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('client_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('client_port', models.PositiveIntegerField()),
                ('dest_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('dest_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, choices=[('TCP', 'TCP'), ('UDP', 'UDP')], max_length=3, null=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('elapsed_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_status', models.CharField(blank=True, choices=[('HIT', 'HIT'), ('MISS', 'MISS'), ('BYPASS', 'BYPASS'), ('EXPIRED', 'EXPIRED'), ('REVALIDATED', 'REVALIDATED')], max_length=11, null=True)),
                ('verdict', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY')], default='ALLOW', max_length=5)),
                ('block_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('match_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY'), ('ALERT', 'ALERT'), ('LOG_ONLY', 'LOG_ONLY')], max_length=10)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rule_match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('engine', models.CharField(max_length=100)),
                ('severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('signature', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'security_alert',
                'managed': False,
            },
        ),
    ]
