# Generated by Django 6.0.2 on 2026-02-12 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('client_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('client_port', models.PositiveIntegerField()),
                ('dest_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('dest_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, choices=[('TCP', 'TCP'), ('UDP', 'UDP')], max_length=3, null=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('elapsed_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_status', models.CharField(blank=True, choices=[('HIT', 'HIT'), ('MISS', 'MISS'), ('BYPASS', 'BYPASS'), ('EXPIRED', 'EXPIRED'), ('REVALIDATED', 'REVALIDATED')], max_length=11, null=True)),
                ('verdict', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY')], default='ALLOW', max_length=5)),
                ('block_reason', models.TextField(blank=True, default='')),
                ('method', models.ForeignKey(blank=True, db_column='method_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='control.httpmethod')),
                ('url', models.ForeignKey(blank=True, db_column='url_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='control.url')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='control.user')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='FirewallEvent',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fw_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('action', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY'), ('ALERT', 'ALERT'), ('LOG_ONLY', 'LOG_ONLY')], max_length=10)),
                ('nat_info', models.JSONField(blank=True, null=True)),
                ('dst_zone', models.ForeignKey(blank=True, db_column='dst_zone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_firewall_events', to='control.zone')),
                ('service', models.ForeignKey(blank=True, db_column='service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewall_events', to='control.service')),
                ('src_zone', models.ForeignKey(blank=True, db_column='src_zone_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_firewall_events', to='control.zone')),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='firewall_events', to='events.request')),
            ],
            options={
                'db_table': 'firewall_event',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('error_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='ERROR', max_length=8)),
                ('message', models.TextField()),
                ('component', models.CharField(max_length=100)),
                ('request', models.ForeignKey(blank=True, db_column='request_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='events.request')),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
        migrations.CreateModel(
            name='RuleMatch',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('match_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY'), ('ALERT', 'ALERT'), ('LOG_ONLY', 'LOG_ONLY')], max_length=10)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='rule_matches', to='events.request')),
                ('rule', models.ForeignKey(db_column='rule_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='control.rule')),
            ],
            options={
                'db_table': 'rule_match',
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('engine', models.CharField(max_length=100)),
                ('severity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('signature', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(db_column='request_id', on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='events.request')),
            ],
            options={
                'db_table': 'security_alert',
            },
        ),
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cache_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size', models.BigIntegerField()),
                ('last_accessed', models.DateTimeField()),
                ('expiration_time', models.DateTimeField()),
                ('url', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='control.url')),
            ],
            options={
                'db_table': 'cache_entry',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('url',), name='cache_entry_url_active_uniq')],
            },
        ),
    ]
