# Generated by Django 6.0.2 on 2026-02-12 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheentry',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cacheentry',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='firewallevent',
            name='action',
            field=models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY')], max_length=5),
        ),
        migrations.AlterField(
            model_name='firewallevent',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='client_port',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rulematch',
            name='action',
            field=models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY')], max_length=5),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
